version: '3.8'

services:
  app:
    image: rendercommunity/render-php:latest
    ports:
      - "8080:8080"
    volumes:
      - ./laravel:/app
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
      - APP_KEY=base64:YOUR_BASE64_ENCODED_KEY
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=your_database_name
      - DB_USERNAME=your_database_username
      - DB_PASSWORD=your_database_password
      - PUSHER_APP_ID=1734857
      - PUSHER_APP_KEY=fda8cde548a674208dc7
      - PUSHER_APP_SECRET=f61721a57f6a71019b09
      - PUSHER_HOST=localhost
      - PUSHER_PORT=443
      - PUSHER_SCHEME=https
      - PUSHER_APP_CLUSTER=mt1


  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=your_mysql_root_password
      - MYSQL_DATABASE=your_database_name
      - MYSQL_USER=your_database_username
      - MYSQL_PASSWORD=your_database_password
    volumes:
      - ./mysql-data:/var/lib/mysql

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./laravel/public:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

networks:
  default:
    external:
      name: public
